export const tools = [
  {
    name: "JPG to PDF",
    route: "/jpg-to-pdf",
    icon: "🖼️",
    description: "Convert JPG images into a single PDF file.",
  },
  {
    name: "PDF Splitter",
    route: "/pdf-splitter",
    icon: "✂️",
    description: "Split PDF into individual pages.",
  },
  {
    name: "Merge PDF",
    route: "/pdf-merge",
    icon: "🔗",
    description: "Combine multiple PDFs into one.",
  },
  {
    name: "Compress PDF",
    route: "/pdf-compress",
    icon: "📉",
    description: "Reduce PDF file size.",
  },
  {
    name: "PDF to JPG",
    route: "/pdf-to-jpg",
    icon: "🖨️",
    description: "Convert PDF pages into JPG images.",
  },
  {
    name: "PDF to Word",
    route: "/pdf-to-word",
    icon: "📄➡️📝",
    description: "Convert PDF documents to Word format.",
  },
  {
    name: "Word to PDF",
    route: "/word-to-pdf",
    icon: "📝➡️📄",
    description: "Convert Word documents to PDF.",
  },
  {
    name: "Image Converter",
    route: "/image-converter",
    icon: "🔄🖼️",
    description: "Convert images between formats (JPG, PNG, etc).",
  },
  {
    name: "Image Resizer",
    route: "/image-resizer",
    icon: "📐",
    description: "Resize images to custom dimensions.",
  },
  {
    name: "Word Counter",
    route: "/word-counter",
    icon: "🔢",
    description: "Count words and characters in your text.",
  },
  {
    name: "Case Converter",
    route: "/case-converter",
    icon: "🔠",
    description: "Convert text to UPPERCASE, lowercase, or Capitalized.",
  },
  {
    name: "AI Summarizer",
    route: "/ai-summarizer",
    icon: "🧠",
    description: "Summarize long text using AI.",
  },
  {
    name: "PDF Watermark",
    route: "/pdf-watermark",
    icon: "💧",
    description: "Add watermark text to your PDF.",
  },
  {
    name: "PDF Signer",
    route: "/pdf-signer",
    icon: "✍️",
    description: "Digitally sign your PDF files.",
  },
  {
    name: "PDF Unlock",
    route: "/pdf-unlock",
    icon: "🔓",
    description: "Remove password from protected PDFs.",
  },
  {
    name: "PDF Protect",
    route: "/pdf-protect",
    icon: "🔐",
    description: "Add password protection to your PDF.",
  },
  {
    name: "Rotate PDF",
    route: "/pdf-rotate",
    icon: "🔄",
    description: "Rotate pages in your PDF file.",
  },
  {
    name: "Organize PDF",
    route: "/pdf-organize",
    icon: "📚",
    description: "Reorder or delete PDF pages.",
  },
  {
    name: "Text to PDF",
    route: "/text-to-pdf",
    icon: "📝➡️📄",
    description: "Convert plain text into a PDF document.",
  },
  {
    name: "HTML to PDF",
    route: "/html-to-pdf",
    icon: "🌐➡️📄",
    description: "Convert HTML code into a PDF file.",
  },
  {
    name: "PDF Reader",
    route: "/pdf-reader",
    icon: "📖",
    description: "Read and extract text from PDF files.",
  },
];
